apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  # Project description
  description: Project to manage all infra applications

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: infra
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true

  roles:
  # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
  # sync privileges to a CI system
  - name: infra-team-role
    description: Full access for infra team except delete option
    policies:
    - p, proj:infra:infra-team-role, applications, create, infra/*, allow
    - p, proj:infra:infra-team-role, applications, update, infra/*, allow
    - p, proj:infra:infra-team-role, applications, sync, infra/*, allow
    - p, proj:infra:infra-team-role, applications, get, infra/*, allow
    - p, proj:infra:infra-team-role, applications, delete, infra/*, deny
    - g, role:infra-team-role
    - g, Exotel:arnifaizaan, role:infra-team-role

    # NOTE: JWT tokens can only be generated by the API server and the token is not persisted
    # anywhere by Argo CD. It can be prematurely revoked by removing the entry from this list.
    jwtTokens: []
      # - iat: 1535390316
