# mysql service headless type
kind: Service
apiVersion: v1
metadata:
  name: beanstalkd-svc
spec:
  selector:
    app: beanstalkd
  type: NodePort
  ports:
  - name: beanstalkd-port
    port: 11300
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: beanstalkd-statefulset
  namespace: default
spec:
  selector:
    matchLabels:
      app: beanstalkd 
  serviceName: "beanstalkd-svc"
  replicas: 1 
  template:
    metadata:
      labels:
        app: beanstalkd 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: beanstalkd
        image: schickling/beanstalkd
        ports:
        - containerPort: 11300
          name: beanstalkd-port
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ROOT_PASSWORD
              name: mysql-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi