---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /
    prometheus.io/port: "8080"
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - name: jenkins-port
      port: 8080
      targetPort: 8080
      nodePort: 32000
