---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authix
  namespace: argocd
spec:
  destination:
    namespace: authix
    server: https://kubernetes.default.svc
  project: mapi
  source:
    path: authix/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
  syncPolicy: {}
