---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: call-state-manager
  namespace: argocd
spec:
  destination:
    namespace: callstatemanager
    server: https://kubernetes.default.svc
  project: voice
  source:
    path: callstatemanager/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
