---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceramix
  namespace: argocd
spec:
  destination:
    namespace: ceramix
    server: https://kubernetes.default.svc
  project: mapi
  source:
    path: ceramix/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
