---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daakiyatrix
  namespace: argocd
spec:
  destination:
    namespace: daakiyatrix
    server: https://kubernetes.default.svc
  project: daakiyatrix
  source:
    path: daakiyatrix/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
