---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frodo
  namespace: argocd
spec:
  destination:
    namespace: frodo
    server: https://kubernetes.default.svc
  project: data
  source:
    path: frodo/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
