---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellibabix-call
  namespace: argocd
spec:
  destination:
    namespace: 'jellibabix'
    server: https://kubernetes.default.svc
  project: data
  source:
    path: jellibabix-call/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
