---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifixwebsocket
  namespace: argocd
spec:
  destination:
    namespace: notifixwebsocket
    server: https://kubernetes.default.svc
  project: mapi
  source:
    path: notifixwebsocket/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
  syncPolicy: {}
