---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zohodesk
  namespace: argocd
spec:
  destination:
    namespace: zohodesk
    server: https://kubernetes.default.svc
  project: mapi
  source:
    path: zohodesk/integration
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/exotel_deployments.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
