FROM proxysql/proxysql:1.4.15

LABEL maintainer="Nikhil Kukatla <nikhil.k@exotel.in>"
LABEL maintainer="Exotel <tech@exotel.in>"

WORKDIR /root

# CMD ["/usr/bin/proxysql", "-c", "/exotel/configs/proxysql.cnf", "-f", "--initial"]