apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth-generic-oauth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  GF_AUTH_GENERIC_OAUTH_CLIENT_ID: {{ .Values.keycloak_id }}
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: {{ .Values.keycloak_secret }}