FROM docker:19.03.3-rc1

RUN apk update && \
  apk add --no-cache --virtual .build-deps && \
  apk add bash && \
  apk add make && \
  apk add curl && \
  apk add openssh && \
  apk -Uuv add groff less python py-pip && \
  pip install awscli && \
  apk --purge -v del py-pip && \
  rm /var/cache/apk/*
