FROM openjdk:7

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y \
    ant

RUN wget http://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz && \
  tar -zxvf apache-maven-3.5.4-bin.tar.gz && \
  rm apache-maven-3.5.4-bin.tar.gz && \
  mv apache-maven-3.5.4 /usr/lib/mvn

ENV PATH /usr/lib/mvn/bin:$PATH 
ENV JAVA_HOME /usr/lib/jvm/java-7-openjdk-amd64/

RUN apt-get install make
