apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: aws-alb-ingress-controller/qa_us3/
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/kubernetes_charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
