apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusteroverprovision
  namespace: argocd
spec:
  destination:
    namespace: overprovisioning
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: cluster-basics/Clusteroverprovisioiner
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/kubernetes_charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
