apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-spot-rescheduler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: cluster-basics/k8s-spot-rescheduler/1.17/k8s-spot-rescheduler
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/kubernetes_charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
