apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  destination:
    namespace: loki-stack
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      valueFiles:
      - values/values.integration.yaml
    path: loki-stack/1.17/loki-stack
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/kubernetes_charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
