apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-pushgateway
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: prometheus-pushgateway/1.17/prometheus-pushgateway/
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/kubernetes_charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
