apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workerpodautoscaler
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: workerpod-autoscaler/integration  
    repoURL: https://cicd-exotel@bitbucket.org/Exotel/kubernetes_charts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
