{
 "title": "K8s-resources cost time series",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(maxaws_namespace_cost, _namespace)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(maxaws_container_cost, _conatiner)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(maxaws_node_cost[60m])) "
    }
   ]
  },
  {
   "title": "Container cost",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (_conatiner) (avg_over_time(maxaws_container_cost{_namespace=\"$namespace\", _conatiner=\"$container\"}[3600s]))",
     "legendFormat": "{{_conatiner}}"
    }
   ]
  },
  {
   "title": "Namespace cost",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (_namespace) (avg_over_time(maxaws_namespace_cost{_namespace=\"$namespace\"}[3600s]))",
     "legendFormat": "{{_namespace}}"
    }
   ]
  }
 ]
}