{
 "title": "Cost/Hour(Node,Namespace,Node)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Cluster Daily Avg Cost",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg_over_time(maxaws_node_cost[60m])) * 24",
     "legendFormat": "Cluster Cost"
    }
   ]
  },
  {
   "title": "Node cost",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (_node)  (avg_over_time(maxaws_node_cost[3600s])) "
    }
   ]
  },
  {
   "title": "Pod cost",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by (_pod,_namespace)  (avg_over_time(maxaws_pod_cost[3600s])) "
    }
   ]
  },
  {
   "title": "Container cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (_conatiner,_namespace)  (avg_over_time(maxaws_container_cost[3600s])) "
    }
   ]
  },
  {
   "title": "Namespace cost",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (_namespace)  (avg_over_time(maxaws_namespace_cost[3600s])) "
    }
   ]
  },
  {
   "title": "CPU Usage (Namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Total CPU vs Usage CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",job=\"kube-state-metrics\"}) "
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) "
    }
   ]
  },
  {
   "title": "Memory Usage in MB (Namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\"}) by (namespace) / 1024 /1024 ",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}