apiVersion: v1
kind: Namespace
metadata:
  name: metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-metrics
  namespace: metrics
  labels:
    app: fluentd-metrics

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-metrics
  namespace: metrics
  labels:
    app: fluentd-metrics
spec:
  minReadySeconds: 0
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fluentd-metrics
  template:
    metadata:
      labels:
        app: fluentd-metrics
    spec:
      hostNetwork: true
      serviceAccount: fluentd-metrics
      serviceAccountName: fluentd-metrics
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: exotelorg/fluentd-kafka:1.1.6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6700
            hostPort: 6700
            name: fluentd-port
            protocol: UDP
        env:
          - name: FLUENT_KAFKA_BROKERS
            value: "kafka-1.internal.exotel.in:9092,kafka-2.internal.exotel.in:9092,kafka-3.internal.exotel.in:9092"
          - name: FLUENT_KAFKA_DEFAULT_TOPIC
            value: "qa"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
