apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: read-only-rbac
subjects:
  - kind: User
    name: testuserkubectlread
    apiGroup: rbac.authorization.k8s.io
  
  - kind: User
    name: shashank.hegde
    apiGroup: rbac.authorization.k8s.io
  
  - kind: User
    name: ajay.paratmandali
    apiGroup: rbac.authorization.k8s.io

  
roleRef:
  kind: ClusterRole
  name:  read-only-cluster-role
  apiGroup: rbac.authorization.k8s.io

