#Alert manager config 

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: null
      ##      routes:
      ##      - match:
      ##          alertname: Watchdog
      ##        receiver: 'null'
    receivers: []

