apiVersion: v1
kind: Namespace
metadata:
  name: auditlog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-audit
  namespace: auditlog
  labels:
    app: fluentd-audit

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-audit
  namespace: auditlog
  labels:
    app: fluentd-audit
spec:
  minReadySeconds: 0
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: fluentd-audit
  template:
    metadata:
      labels:
        app: fluentd-audit
    spec:
      hostNetwork: true
      serviceAccount: fluentd-audit
      serviceAccountName: fluentd-audit
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: exotelorg/fluentd-auditlog:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 6710
            hostPort: 6710
            name: fluentd-port
            protocol: UDP
        env:
          - name: FLUENT_KAFKA_BROKERS
            value: "auditlog-kafka-1.internal.exotel.in:9092"
          - name: FLUENT_KAFKA_DEFAULT_TOPIC
            value: "app_audit_logs"
          - name: FLUENTD_PORT
            value: "6710"
          - name: FLUENTD_TAG
            value: "app_audit_logs"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
      terminationGracePeriodSeconds: 30
